[package]
name = "sandbox-configurations"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
indicatif = "*"
colored = "*"

[lints]
workspace = true
