# https://doc.rust-lang.org/nightly/clippy/lint_configuration.html

# absolute-paths-allowed-crates = []
absolute-paths-max-segments = 0
# accept-comment-above-attributes = true
# accept-comment-above-statement = true
# allow-comparison-to-zero = true
allow-dbg-in-tests = true
# allow-expect-in-tests = false
# allow-mixed-uninlined-format-args = true
# allow-one-hash-in-raw-strings = false
# allow-panic-in-tests = false
# allow-print-in-tests = false
# allow-private-module-inception = false
# allow-renamed-params-for = [".."]
allow-unwrap-in-tests = true
# allow-useless-vec-in-tests = false
# allowed-dotfiles = []
# allowed-duplicate-crates = []
# allowed-idents-below-min-chars = [".."]
# allowed-prefixes = [".."]
# allowed-scripts = ["Latin"]
# allowed-wildcard-imports = []
# arithmetic-side-effects-allowed = []
# arithmetic-side-effects-allowed-binary = []
# arithmetic-side-effects-allowed-unary = []
# array-size-threshold = 16384
# avoid-breaking-exported-api = true
# await-holding-invalid-types = []
# cargo-ignore-publish = false
check-private-items = true
# cognitive-complexity-threshold = 25
# disallowed-macros = []
# disallowed-methods = []
# disallowed-names = [".."]
# disallowed-types = []
# doc-valid-idents = [".."]
# enable-raw-pointer-heuristic-for-send = true
# enforce-iter-loop-reborrow = false
# enforced-import-renames = []
enum-variant-name-threshold = 0
# enum-variant-size-threshold = 200
# excessive-nesting-threshold = 0
# future-size-threshold = 16384
# ignore-interior-mutability = ["bytes::Bytes"]
# large-error-threshold = 128
# lint-inconsistent-struct-field-initializers = false
# literal-representation-threshold = 16384
# matches-for-let-else = "WellKnownTypes"
# max-fn-params-bools = 3
# max-include-file-size = 1000000
# max-struct-bools = 3
# max-suggested-slice-pattern-length = 3
max-trait-bounds = 42
# min-ident-chars-threshold = 1
# missing-docs-in-crate-items = false
# module-item-order-groupings = [["modules", ["extern_crate", "mod", "foreign_mod"]], ["use", ["use"]], ["macros", ["macro"]], ["global_asm", ["global_asm"]], ["UPPER_SNAKE_CASE", ["static", "const"]], ["PascalCase", ["ty_alias", "enum", "struct", "union", "trait", "trait_alias", "impl"]], ["lower_snake_case", ["fn"]]]
# msrv =
# pass-by-value-size-limit = 256
pub-underscore-fields-behavior = "PubliclyExported"
# semicolon-inside-block-ignore-singleline = false
# semicolon-outside-block-ignore-multiline = false
# single-char-binding-names-threshold = 4
# source-item-ordering = ["enum", "impl", "module", "struct", "trait"]
# stack-size-threshold = 512000
# standard-macro-braces = []
struct-field-name-threshold = 0
# suppress-restriction-lint-in-const = false
# too-large-for-stack = 200
too-many-arguments-threshold = 3
# too-many-lines-threshold = 100
# trait-assoc-item-kinds-order = ["const", "type", "fn"]
# trivial-copy-size-limit = 
# type-complexity-threshold = 250
# unnecessary-box-size = 128
# unreadable-literal-lint-fractions = true
# upper-case-acronyms-aggressive = false
# vec-box-size-threshold = 4096
# verbose-bit-mask-threshold = 1
# warn-on-all-wildcard-imports = false
# warn-unsafe-macro-metavars-in-private-macros = false
