[package]
name = "cli-configurations"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
archery = { workspace = true }
indicatif = "0.17"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros", "time"] }

[lints]
workspace = true
