[package]
name = "cli-configurations"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
indicatif = "0.18"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros", "time"] }
regex = "1"

[lints]
workspace = true
