[package]
name = "cli-configurations"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
domain = { path = "../../core/domain" }
use-cases = { path = "../../core/use-cases" }
infrastructures = { path = "../../infrastructures" }

anyhow = { workspace = true }
clap = "4.5.41"
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }

[lints]
workspace = true
