[package]
name = "use-cases"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
async-stream = { workspace = true }
futures-core = "0.3.31"
futures-util = "0.3.31"
tokio = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
triomphe = { workspace = true }

domain = { path = "../domain" }

[lints]
workspace = true
