[package]
name = "use-cases"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
archery = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
