[package]
name = "infrastructures"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
domain = { path = "../core/domain" }
use-cases = { path = "../core/use-cases" }

async-stream = { workspace = true }
async-trait = { workspace = true }
futures-core = { workspace = true }
lofty = "0.22.4"

[lints]
workspace = true
