name: Build

on:
  workflow_call:

jobs:
  cargo-check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        channel:
          - stable
          - beta
          - nightly

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo check --workspace --all-targets --all-features
