name: CI

on:
  push:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs:
      - lint
    uses: ./.github/workflows/build.yml

  test:
    needs:
      - lint
      - build
    uses: ./.github/workflows/test.yml

  dependencies-check:
    needs:
      - lint
      - build
      - test
    uses: ./.github/workflows/dependencies-check.yml
