name: Lint

on:
  workflow_call:

jobs:
  cargo-fmt:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - nightly

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: rustfmt

      - run: cargo fmt --all -- --check
  
  cargo-clippy:
    needs:
      - cargo-fmt

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        channel:
          - nightly

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: clippy

      - run: cargo clippy --workspace --all-targets --all-features
